version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: yuri/technical-challenge
    container_name: technical-challenge
    ports: 
      - '3000:3000'
  